[WinEventLog://Security]
index = windows

[WinEventLog://System]
index = windows

[WinEventLog://Application]
index = windows

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = sysmon